### ISSUE TITLE
Fix install command on README

### ISSUE THREAD

**Issue by eduardoweiland** [bloodf/sass-semantic-ui#2]
Hello @bloodf, thanks for the awesome work.

The install command in the README file is wrong. First, the package name is from another Semantic UI SASS project and not from this one. So,

```yarn add --dev semantic-ui-sass```

should be

```yarn add --dev sass-semantic-ui```

But this is not enough to get color variables working. I had to install directly from master with

```npm i --save-dev github:bloodf/sass-semantic-ui#master```

**Comment by bloodf** [comment]
Fixed!
